Trying to fix this error: ```
2021-12-03 05:28:21,177,177ms [PID: 3072334] workers.pull_request_worker.9250 [INFO] Updated rate limit, you have: 4773 requests remaining.
2021-12-03 05:28:21,177,177ms [PID: 3072334] workers.pull_request_worker.9250 [INFO] Request returned a dict!
2021-12-03 05:28:21,178,178ms [PID: 3072334] workers.pull_request_worker.9250 [INFO] Contributor data: {'login': 'ksankaranara-vmw', 'id': 94123215, 'node_id': 'U_kgDOBZw0zw', 'avatar_url': 'https://avatars.githubusercontent.com/u/94123215?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ksankaranara-vmw', 'html_url': 'https://github.com/ksankaranara-vmw', 'followers_url': 'https://api.github.com/users/ksankaranara-vmw/followers', 'following_url': 'https://api.github.com/users/ksankaranara-vmw/following{/other_user}', 'gists_url': 'https://api.github.com/users/ksankaranara-vmw/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ksankaranara-vmw/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ksankaranara-vmw/subscriptions', 'organizations_url': 'https://api.github.com/users/ksankaranara-vmw/orgs', 'repos_url': 'https://api.github.com/users/ksankaranara-vmw/repos', 'events_url': 'https://api.github.com/users/ksankaranara-vmw/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ksankaranara-vmw/received_events', 'type': 'User', 'site_admin': False, 'name': None, 'company': None, 'blog': '', 'location': None, 'email': None, 'hireable': None, 'bio': None, 'twitter_username': None, 'public_repos': 2, 'public_gists': 0, 'followers': 0, 'following': 0, 'created_at': '2021-11-11T14:21:43Z', 'updated_at': '2021-12-03T05:36:10Z'}
2021-12-03 05:28:21,178,178ms [PID: 3072334] workers.pull_request_worker.9250 [INFO] Contributor data: {'login': 'ksankaranara-vmw', 'id': 94123215, 'node_id': 'U_kgDOBZw0zw', 'avatar_url': 'https://avatars.githubusercontent.com/u/94123215?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ksankaranara-vmw', 'html_url': 'https://github.com/ksankaranara-vmw', 'followers_url': 'https://api.github.com/users/ksankaranara-vmw/followers', 'following_url': 'https://api.github.com/users/ksankaranara-vmw/following{/other_user}', 'gists_url': 'https://api.github.com/users/ksankaranara-vmw/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ksankaranara-vmw/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ksankaranara-vmw/subscriptions', 'organizations_url': 'https://api.github.com/users/ksankaranara-vmw/orgs', 'repos_url': 'https://api.github.com/users/ksankaranara-vmw/repos', 'events_url': 'https://api.github.com/users/ksankaranara-vmw/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ksankaranara-vmw/received_events', 'type': 'User', 'site_admin': False, 'name': None, 'company': None, 'blog': '', 'location': None, 'email': None, 'hireable': None, 'bio': None, 'twitter_username': None, 'public_repos': 2, 'public_gists': 0, 'followers': 0, 'following': 0, 'created_at': '2021-11-11T14:21:43Z', 'updated_at': '2021-12-03T05:36:10Z'}
2021-12-03 05:28:21,189,189ms [PID: 3072334] workers.pull_request_worker.9250 [INFO] there was a collision caught ....
2021-12-03 05:28:21,190,190ms [PID: 3072334] workers.pull_request_worker.9250 [INFO] Traceback (most recent call last):
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "GL-cntrb-LOGIN-UNIQUE"
DETAIL:  Key (cntrb_login)=(ksankaranara-vmw) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sean/github/augur-vmware/vmware-loader/workers/worker_git_integration.py", line 469, in enrich_cntrb_id
    self.db.execute(self.contributors_table.insert().values(cntrb))
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/sean/github/virtualenv/vmware/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "GL-cntrb-LOGIN-UNIQUE"
DETAIL:  Key (cntrb_login)=(ksankaranara-vmw) already exists.

[SQL: INSERT INTO contributors (cntrb_login, cntrb_email, cntrb_full_name, cntrb_company, cntrb_created_at, cntrb_location, cntrb_canonical, cntrb_last_used, gh_user_id, gh_login, gh_url, gh_html_url, gh_node_id, gh_avatar_url, gh_gravatar_id, gh_followers_url, gh_following_url, gh_gists_url, gh_starred_url, gh_subscriptions_url, gh_organizations_url, gh_repos_url, gh_events_url, gh_received_events_url, gh_type, gh_site_admin, tool_source, tool_version, data_source) VALUES (%(cntrb_login)s, %(cntrb_email)s, %(cntrb_full_name)s, %(cntrb_company)s, %(cntrb_created_at)s, %(cntrb_location)s, %(cntrb_canonical)s, %(cntrb_last_used)s, %(gh_user_id)s, %(gh_login)s, %(gh_url)s, %(gh_html_url)s, %(gh_node_id)s, %(gh_avatar_url)s, %(gh_gravatar_id)s, %(gh_followers_url)s, %(gh_following_url)s, %(gh_gists_url)s, %(gh_starred_url)s, %(gh_subscriptions_url)s, %(gh_organizations_url)s, %(gh_repos_url)s, %(gh_events_url)s, %(gh_received_events_url)s, %(gh_type)s, %(gh_site_admin)s, %(tool_source)s, %(tool_version)s, %(data_source)s) RETURNING contributors.cntrb_id]
[parameters: {'cntrb_login': 'ksankaranara-vmw', 'cntrb_email': None, 'cntrb_full_name': None, 'cntrb_company': None, 'cntrb_created_at': '2021-11-11T14:21:43Z', 'cntrb_location': None, 'cntrb_canonical': None, 'cntrb_last_used': '2021-12-03T05:36:10Z', 'gh_user_id': 94123215, 'gh_login': 'ksankaranara-vmw', 'gh_url': 'https://api.github.com/users/ksankaranara-vmw', 'gh_html_url': 'https://github.com/ksankaranara-vmw', 'gh_node_id': 'U_kgDOBZw0zw', 'gh_avatar_url': 'https://avatars.githubusercontent.com/u/94123215?v=4', 'gh_gravatar_id': '', 'gh_followers_url': 'https://api.github.com/users/ksankaranara-vmw/followers', 'gh_following_url': 'https://api.github.com/users/ksankaranara-vmw/following{/other_user}', 'gh_gists_url': 'https://api.github.com/users/ksankaranara-vmw/gists{/gist_id}', 'gh_starred_url': 'https://api.github.com/users/ksankaranara-vmw/starred{/owner}{/repo}', 'gh_subscriptions_url': 'https://api.github.com/users/ksankaranara-vmw/subscriptions', 'gh_organizations_url': 'https://api.github.com/users/ksankaranara-vmw/orgs', 'gh_repos_url': 'https://api.github.com/users/ksankaranara-vmw/repos', 'gh_events_url': 'https://api.github.com/users/ksankaranara-vmw/events{/privacy}', 'gh_received_events_url': 'https://api.github.com/users/ksankaranara-vmw/received_events', 'gh_type': 'User', 'gh_site_admin': False, 'tool_source': 'GitHub Pull Request Worker', 'tool_version': '1.0.0', 'data_source': 'GitHub API'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

2021-12-03 05:28:21,264,264ms [PID: 3072334] workers.pull_request_worker.9250 [ERROR] Couldn't find contributor in database. Something has gone very wrong. Augur ran into a contributor that is unable to be inserted into the contributors table but is also not present in that table.
2021-12-03 05:28:21,264,264ms [PID: 3072334] workers.pull_request_worker.9250 [DEBUG] Pull Requests model failed with 'cntrb_id'.
2021-12-03 05:28:21,265,265ms [PID: 3072334] workers.pull_request_worker.9250 [DEBUG] Traceback (most recent call last):
  File "/home/sean/github/augur-vmware/vmware-loader/workers/pull_request_worker/pull_request_worker.py", line 594, in pull_requests_model
    pk_source_prs = self._get_pk_source_prs()
  File "/home/sean/github/augur-vmware/vmware-loader/workers/pull_request_worker/pull_request_worker.py", line 567, in _get_pk_source_prs
    pk_source_increment_insert(source_prs,pr_action_map)
  File "/home/sean/github/augur-vmware/vmware-loader/workers/pull_request_worker/pull_request_worker.py", line 422, in pk_source_increment_insert
    inc_source_prs['insert'] = self.enrich_cntrb_id(
  File "/home/sean/github/augur-vmware/vmware-loader/workers/worker_git_integration.py", line 496, in enrich_cntrb_id
    'cntrb_id': int(data['cntrb_id']), # came through as a float. Fixed 11/28/2021, SPG
KeyError: 'cntrb_id'

```